EMPTY/EmployeeManagement/EmployeeManagement.UI/EmployeeManagement.UI/Controllers/EmployeeLeaveTypesController.cs
using EmployeeManagement.BusinesEngine.Contracts;
using EmployeeManagement.BusinesEngine.Implementaion;
using EmployeeManagement.Common.ConstantModels;
using EmployeeManagement.Common.VModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeManagement.UI.Controllers
{
    [Authorize(Roles =ResultConstant.Admin_Role)]
    public class EmployeeLeaveTypesController : Controller
    {
        private readonly IEmployeeLeaveTypeBusinessEngine _employeeLeaveTypeBusinessEngine;

        public EmployeeLeaveTypesController(IEmployeeLeaveTypeBusinessEngine employeeLeaveTypeBusinessEngine)
        {
            _employeeLeaveTypeBusinessEngine = employeeLeaveTypeBusinessEngine;
        }
        public IActionResult Index()
        {
            var data = _employeeLeaveTypeBusinessEngine.GetAllEmployeeLeaveTypes();
            if (data.IsSucces == true)
            {
                var result = data.Data;
                return View(result);
            }
            return View();
        }
        [HttpGet]
		public IActionResult Create()
		{
			
			return View();
		}
        [HttpPost]
		public IActionResult Create(EmployeeLeaveTypeVM model)
		{
            if (ModelState.IsValid)
            {
                var data = _employeeLeaveTypeBusinessEngine.CreateEmployeeLeaveType(model);
                if (data.IsSucces)
                {
                    return RedirectToAction("Index");
                }
                return View(model);
			}
            else 
                return View(model);
			

			
		}

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (id < 0)
                return View();
            var data = _employeeLeaveTypeBusinessEngine.GetAllEmployeeLeaveType(id);
            if (data.IsSucces)
              return View(data.Data);
            return View();

		}
        [ValidateAntiForgeryToken]
		[HttpPost]
		public IActionResult Edit(EmployeeLeaveTypeVM model)
		{
			if(ModelState.IsValid) 
            {
            var data = _employeeLeaveTypeBusinessEngine.EditEmployeeLeaveType(model);
                if (data.IsSucces)
                {
                    return RedirectToAction("Index");
                }
                return View(model);
                
            }
			else
				return View(model);

		}

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            if (id <= 0)
                return Json(new { success = false, message = "Silmek İçin Kayıt Seçiniz" });

            var data = _employeeLeaveTypeBusinessEngine.RemoveEmployeeLeaveType(id);

            if (data.IsSucces)
                return Json(new { success = data.IsSucces, message = data.Message });
            else
                return Json(new { success = data.IsSucces, message = data.Message });

        }
    }
}

EMPTY/EmployeeManagement/EmployeeManagement.UI/EmployeeManagement.UI/Views/EmployeeLeaveTypes/Create.cshtml
@model EmployeeManagement.Common.VModels.EmployeeLeaveTypeVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-content">
	<div class="main-content-inner">


		<div class="page-content">
		


			<div class="row">
				<div class="col-xs-12">
					<!-- PAGE CONTENT BEGINS -->
				
					<form class="form-horizontal aside" asp-action="Create">
						<div asp-validation-summary="ModelOnly" class="text-danger"></div>
						<div class="form-group">
							<label class="col-sm-3 control-label no-padding-right" asp-for="Name"> İzin Tipi</label>

							<div class="col-sm-9">
								<input asp-for="Name" type="text" id="form-field-1" placeholder="Tatil Sebebi Türü" class="col-xs-10 col-sm-5" />
								<span asp-validation-for="Name"></span>
							</div>
							<label class="col-sm-3 control-label no-padding-right" asp-for="Name">Sabit Gün Sayısı</label>
							<div class="col-sm-9">
								<input asp-for="DefaultDays" type="number" min="0" max="15" id="form-field-1" placeholder="Sabit Gün Sayısı" class="col-xs-10 col-sm-5" />
								<span asp-validation-for="DefaultDays"></span>
							</div>
						</div>


						<div class="clearfix form-actions">
					<div class="col-md-offset-3 col-md-9">
							
					<input type="submit" value="Create" class="btn btn-info col-xs-3" />
						</div>
						</div>
					</form>
			</div>
		</div>
	</div>
</div>
</div>
@section Scripts{
	<partial name="_ValidationScriptsPartial" />
}

EMPTY/EmployeeManagement/EmployeeManagement.UI/EmployeeManagement.UI/Views/EmployeeLeaveTypes/Edit.cshtml
@model EmployeeManagement.Common.VModels.EmployeeLeaveTypeVM

@{
    ViewData["Title"] = "Çalışan İzin Tipi Güncelleme";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

	<form class="form-horizontal aside" asp-action="Edit">
	@Html.HiddenFor(x=>Model.Id)
		<div asp-validation-summary="ModelOnly" class="text-danger"></div>
		<div class="form-group">
			<label class="col-sm-3 control-label no-padding-right" asp-for="Name"> İzin Tipi</label>

			<div class="col-sm-9">
				<input asp-for="Name" type="text" id="form-field-1" placeholder="Username" class="col-xs-10 col-sm-5" />
				<span asp-validation-for="Name"></span>
			</div>
		</div>


		<div class="clearfix form-actions">
			<div class="col-md-offset-3 col-md-9">

				<input type="submit" value="Edit" class="btn btn-info col-xs-3" />
			</div>
		</div>
	</form>

EMPTY/EmployeeManagement/EmployeeManagement.UI/EmployeeManagement.UI/Views/EmployeeLeaveTypes/Index.cshtml
@model IEnumerable<EmployeeManagement.Common.VModels.EmployeeLeaveTypeVM>

@{
    ViewData["Title"] = "EmployeeTypeListView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-header">
    <h3>
        <small>
            <i class="ace-icon fa fa-angle-double-right"></i>
            Çalışan İzin Takip Listesi
        </small>
    </h3>
</div>


<br />
<My-Email mail-to="ertugrulyilmaz">Mail Gönder</My-Email>
<div class="col-6 text-left text-white">
    <a class="btn btn-success" asp-controller="EmployeeLeaveTypes" asp-action="Create">Tip Ekle</a>
</div>
<br />
<div class="row">
    <div class="col-xs-12">
        <table id="simple-table" class="table  table-bordered table-hover">
            <thead>
                <tr>
                    <th>Liste İsmi</th>
                    <th>Oluşturulma Tarihi</th>
                    <th>İşlemler</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td> @item.Name</td>
                        <td>@item.DateCreated</td>
                        <td>
                            <div class="hidden-sm hidden-xs btn-group">
                                @*<button class="btn btn-xs btn-info">
                                        <i class="ace-icon fa fa-pencil bigger-120"></i>
                                    </button>*@
                                <a class="btn btn-xs btn-info" asp-controller="EmployeeLeaveTypes" asp-action="Edit" asp-route-id="@item.Id">

                                    <i class="ace-icon fa fa-pencil bigger-120"></i>
                                </a>
                                <a class="btn btn-xs btn-danger" id="btnRemove" data-id="@item.Id">
                                    <i class="ace-icon fa fa-trash bigger-120"></i>
                                </a>
                                <button class="btn btn-xs btn-warning">
                                    <i class="ace-icon fa fa-flag bigger-120"></i>
                                </button>
                            </div>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div><!-- /.span -->
</div>

@section Scripts{

    <script type="text/javascript">
        $(document).ready(function () {

            $("#btnRemove").on("click", function () {
                var id = $("#btnRemove").data("id");

                swal({
                    title: 'Silmek İstediğinize Emin Misiniz?',
                    text: 'Silinen Data Geri Alınamaz!',
                    icon: 'warning',
                    buttons: true,
                    dangerMode: true
                }).then((willDelete) => {
                    if (willDelete) {
                        $.ajax({
                            type: "DELETE",
                            url: "/EmployeeLeaveTypes/Delete/" + id,
                            success: function (data) {
                                if (data.success) {
                                    toastr.success(data.message);
                                    location.reload();
                                } else {
                                    toastr.error(data.message);
                                }
                            }

                        });
                    }
                });
            });
        });
    </script>

}